---
title: "Postmortem NYPP Mars 2025"
author: "Zineddine Aliche"
date: today
toc: true
jupyter: python3
format:
  html:
    embed-resources: true
    code-tools: true
    grid:
    #   margin-width: 0px  # Reduces side margins
      body-width: 1400px  # Adjusts main content width (default is ~800px)
execute:
  echo: true  # Keep code visible by default
  code-tools: true  # Add show/hide button for each code block

---

## 🛠️ Points à discuter et Projets

- Nouveau projet de changement de la topologie.


<!-- Importation des librairies et initalisation de la connection -->
```{python}
#| code-fold: true
# Import necessary libraries
from services import snowflake_queries as sq
from components import graph_utils as gu, constraint_utils as cu
import plotly.graph_objects as go
from services.database_connection import init_connection
from itables import show, JavascriptFunction
import ipywidgets as widgets

conn=init_connection()
```

## 📈 Evolution de la load et du vents

- La load en monthly est généralement bien estimée au milieu du mois et un peu surestimée en fin de mois
- Le vent est généralement sous-estimée en monthly.

```{python}
#| code-fold: true

df_Load=sq.get_Load(['NYPP_1DA_Default', 'NYPP_1MA_Default', 'NYPP_1MA_LoadMin','NYPP_1MA_LoadMax']
                  ,'2020-01-01'
                  ,'2025-03-31'
                  ,conn
                  )
df_Wind=sq.get_Wind(['NYPP_1DA_Default','NYPP_1MA_Default','NYPP_1MA_WindMin','NYPP_1MA_WindMax']
                  ,'2020-01-01'
                  ,'2025-03-31'
                  ,conn
                  )

gu.create_graph_load(df_Load,'TOTAL','2025-03-01','2025-03-31')
gu.create_graph_wind(df_Wind,'2025-03-01','2025-03-31')
```



## 𝄜 Top contraintes du mois

```{python}
#| code-fold: true

df_PM=sq.get_PostMortem(1
                        ,'2025-03-01'
                        ,'2025-03-31'
                        ,['NYPP_1MA_Default', 'NYPP_1MA_AvgHistSP', 'NYPP_1MA_DL_AvgSP']
                        ,conn)

df_PM.fillna(0,inplace=True)
exclude_columns = ["CID_MAG", "CID_CES", "CONSTRAINTNAME","CONTINGENCYNAME"]

# Apply formatting to all other columns
for col in df_PM.columns:
    if col not in exclude_columns:
        df_PM[col] = df_PM[col].apply(lambda x: f"${x:,}")

# Apply formatting to all other numeric columns


show(df_PM,
    classes="compact",
    column_filters="header", 
    layout={"topEnd": None}, 
    style="font-size: 12px;",
    )
```


## 🕵️ Analyses des contraintes
```{python}
#| code-fold: true

# paramètres généraux
pool_id=1
ftrstartdate='2025-03-01'
ftrenddate='2025-03-31'
histostartdate='2025-03-01'
histoenddate='2025-03-31'
scenario_flows=['NYPP_1MA_Default','NYPP_1DA_Default','NYPP_1MA_AvgHistSP', 'NYPP_1MA_DL_AvgtSP' ]
scenario_first_priority='NYPP_1DA_Default'
scenario_sf=['NYPP_1MA_Default','NYPP_1DA_Default']
scenario_histo_sp=['NYPP_1MA_Default','NYPP_1DA_Default',
                    'NYPP_1MA_AvgHistSP',
                    'NYPP_1MA_DL_AvgtSP'
                    ]
```

<details>
  <summary> 311100 GREENWD  138 VERNON   138 1 GOETHALS-FRESHKLS_345_22_25337</summary>

**Analyse :**

- Captée uniquement par le 1DA_LD, où la limite a baissé de 259MW à 50MW.
- L'outage 25475 (GOWANUS 345KV - GOWANUS138 KV) a été manquées en monthly (un outage qui redirige environ 29MW sur la ligne).
- Selon Dayzer, c'est une contrainte drivée par la load dans NYC et soulagée principalement par l'unité Arthur Kill ST 2, l'outage 25476 (GOWANUSN 345KV - GOWANUSN 138KV) met aussi environ 30MW de pression sur la ligne.


```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      10001492,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```

</details> 

<details>
  <summary>310811   BUCHAN_N 345 BUCHAN_N 138 1 LADENTWN-BUCHAN_S_345_Y88_25425</summary>


**Analyse :**

- Contrainte mal mappée : la contrainte qui a bindé au marché est BUCHAN_N 345 BUCHAN_N 138 1:LOVETT__-BUCHAN_S_345_Y88_(25425). Dans notre mapping, on l’a associée à la contrainte BUCHAN_N 345 BUCHAN_N 138 1 LADENTWN-BUCHAN_S_345_Y88_25425. J’ai vérifié dans les fichiers de contingence du marché, et cette contingence (qui est une line) n’existe pas dans Dayzer. Je vais l’ajouter dans le modèle et corriger la table de mapping avant de lancer le prochain round des annuelles.
- Pour la contrainte BUCHAN_N 345 BUCHAN_N 138 1 LADENTWN-BUCHAN_S_345_Y88_25425, la ligne principale était prévue en outage en monthly entre le 3 et le 8 mars 2025, mais l’outage a finalement été déplacé du 6 au 10 mars en daily. Cette contrainte n’a pas bindé au marché.
- La contrainte est principalement impactée par la load dans NYC et LI, et soulagée par les génératrices non renouvelables.


```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      10001226,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```

</details> 


<details>
  <summary>310863   CODINGTN 115 MONTRFL  115 1 SCB:OAKDALE(31/B322):31&BK3_25728</summary>

**Analyse :**

- Contrainte bien captée par les scénarions 1DA et par quelques scénarios 1MA.
- Les flows sont généralement très proche de la limite, mais la contrainte ne bind pas en monthly dans Dayzer
- Selon Dayzer, les Imports/Exports vers PJM sont le premier facteur qui met de la pression sur la contrainte. 


```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      10001278,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```

</details> 
