---
title: "Postmortem NEPOOL Novembre 2025"
author: "Nicolas Leblanc"
date: today
toc: true
jupyter: python3
format:
  html:
    embed-resources: true
    code-tools: true
    grid:
    #   margin-width: 0px  # Reduces side margins
      body-width: 1400px  # Adjusts main content width (default is ~800px)
execute:
  echo: true  # Keep code visible by default
  code-tools: true  # Add show/hide button for each code block

---

## 🛠️ Points à discuter et Projets

- Application des prébis, accessible via l'url : https://bidanalysis.magitdev.com/.


<!-- Importation des librairies et initalisation de la connection -->
```{python}
#| code-fold: true
# Import necessary libraries
from services import snowflake_queries as sq
from components import graph_utils as gu, constraint_utils as cu
import plotly.graph_objects as go
from services.database_connection import init_connection
from itables import show, JavascriptFunction
import ipywidgets as widgets
from IPython.display import Image, display
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
conn=init_connection()
```

## 📈 Evolution de la load et du vents
<!-- - La LoadMin est plus adapté au début du mois, le LoadMax l'est plus vers la fin du mois.
- Au début (1-7 septembre) et à la fin du mois (22-30 septembre) la différence entre le daily et le monthly (8-21 septembre) est plus petit qu'au milieu du mois. -->
- La génération totale est cyclique.

```{python}
# | code-fold: true
market = 'NEPOOL'
start_date = '2025-11-01'
end_date = '2025-11-30'
pool_id = 3
df_Load=sq.get_Load([f'{market}_1DA_Default', f'{market}_1MA_Default', f'{market}_1MA_LoadMin',f'{market}_1MA_LoadMax']
                  ,'2020-01-01'
                  ,end_date
                  ,conn
                  )
```

- La génération de vent n'est pas cyclique.
<!-- - Le monthly et le daily pour le vent sont similaieres au scénario WindMin au milieu du mois, mais ils diffèrent pour le reste du mois (11-20 septembre). -->

```{python}
# | code-fold: true
df_Wind=sq.get_Wind([f'{market}_1DA_Default',f'{market}_1MA_Default',f'{market}_1MA_WindMin',f'{market}_1MA_WindMax']
                  ,'2020-01-01'
                  ,end_date
                  ,conn
                  )

gu.create_graph_load(df_Load,'TOTAL',start_date,end_date)
gu.create_graph_wind(df_Wind,start_date,end_date)
```

## Métriques

```{python}
# | echo: false

query = f"""
SELECT *
FROM TABLE(
    MAGSNOWFLAKE.DAYZER.FN_METRICS_MONTHLY(
        3,
        ARRAY_CONSTRUCT('NEPOOL_1MA_AvgHistSP','NEPOOL_1MA_Default','NEPOOL_1MA_DL_AvgSP'),
        DATE('2024-04-01'),
        DATE('{end_date}'),
        50
    )
)
"""

df_metriques = pd.read_sql(query, conn)

metrics = [
    "PCT_CAPTE_DU_SP_TOTAL_CUTOFF",
    "PCT_FP_SUP_CUTOFF_DZR",
    "AVG_ERR_ABS_TP"
]

scenarios = [
    "NEPOOL_1MA_AvgHistSP",
    "NEPOOL_1MA_Default",
    "NEPOOL_1MA_DL_AvgSP"
]

df_metriques = df_metriques[df_metriques["SCENARIONAME"].isin(scenarios)]


```

### PCT_CAPTE_DU_SP_TOTAL_CUTOFF

- Pourcentage du SP capté par scénario (CUTOFF 50$): uniquement pour les contraintes captées par Dayzer et qui ont bindé dans le marché, par rapport au SP total du marché
- 100*SUM(ABS(SP_MKT) uniquement celle captées par Dayzer et dont le SP_DZR est supérieur au CutOff)/SUM(ABS(SP_MKT de toutes les contraintes) )

```{python}
# | echo: false

metric = "PCT_CAPTE_DU_SP_TOTAL_CUTOFF"

# plt.figure(figsize=(12, 6))

# for scenario in scenarios:
#     temp = df_metriques[df_metriques["SCENARIONAME"] == scenario]
#     plt.plot(temp["FTRDATE"], temp[metric], label=scenario)

# plt.title(metric)
# plt.xlabel("Date", fontsize=14, fontweight="bold", labelpad=15)
# plt.ylabel("PCT (%)", fontsize=14, fontweight="bold", labelpad=15)
# plt.legend()
# plt.grid(True)
# ax = plt.gca()
# ax.xaxis.set_major_locator(mdates.MonthLocator())
# ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
# plt.xticks(rotation=45)
# plt.show()

fig = go.Figure()

for scenario in scenarios:
    temp = df_metriques[df_metriques["SCENARIONAME"] == scenario]
    fig.add_trace(go.Scatter(
        x=temp["FTRDATE"],
        y=temp[metric],
        mode="lines",
        name=scenario
    ))

fig.update_layout(
    title=metric,
    xaxis_title="Date",
    yaxis_title="PCT (%)",
    template="plotly_white"
)

fig.show()

```

### PCT_FP_SUP_CUTOFF_DZR

- Pourcentage des faux positifs: Nombre des contraintes qui bindent dans Dayzer et qui ne bindent pas dans le marché, divisé par le nombre total de contrainte qui bindent dans Dayzer avec ABS(SP_DZR) >= CutOff (=50$)

```{python}
# | echo: false

metric = "PCT_FP_SUP_CUTOFF_DZR"

fig = go.Figure()

for scenario in scenarios:
    temp = df_metriques[df_metriques["SCENARIONAME"] == scenario]
    fig.add_trace(go.Scatter(
        x=temp["FTRDATE"],
        y=temp[metric],
        mode="lines",
        name=scenario
    ))

fig.update_layout(
    title=metric,
    xaxis_title="Date",
    yaxis_title="PCT (%)",
    template="plotly_white"
)

fig.show()

# plt.figure(figsize=(12, 6))

# for scenario in scenarios:
#     temp = df_metriques[df_metriques["SCENARIONAME"] == scenario]
#     plt.plot(temp["FTRDATE"], temp[metric], label=scenario)

# plt.title(metric)
# plt.xlabel("Date", fontsize=14, fontweight="bold", labelpad=15)
# plt.ylabel("PCT (%)", fontsize=14, fontweight="bold", labelpad=15)
# plt.legend()
# plt.grid(True)
# ax = plt.gca()
# ax.xaxis.set_major_locator(mdates.MonthLocator())
# ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
# plt.xticks(rotation=45)
# plt.show()
    
```

### AVG_ERR_ABS_TP

- Moyenne des erreurs absolues pour les vrais positifs: AVG(ABS(ABS(SP_MKT)-ABS(SP_DZR)))

```{python}
# | echo: false

metric = "AVG_ERR_ABS_TP"

# plt.figure(figsize=(12, 6))

# for scenario in scenarios:
#     temp = df_metriques[df_metriques["SCENARIONAME"] == scenario]
#     plt.plot(temp["FTRDATE"], temp[metric], label=scenario)

# plt.title(metric)
# plt.xlabel("Date", fontsize=14, fontweight="bold", labelpad=15)
# plt.ylabel("PCT (%)", fontsize=14, fontweight="bold", labelpad=15)
# plt.legend()
# plt.grid(True)
# ax = plt.gca()
# ax.xaxis.set_major_locator(mdates.MonthLocator())
# ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
# plt.xticks(rotation=45)
# plt.show()

fig = go.Figure()

for scenario in scenarios:
    temp = df_metriques[df_metriques["SCENARIONAME"] == scenario]
    fig.add_trace(go.Scatter(
        x=temp["FTRDATE"],
        y=temp[metric],
        mode="lines",
        name=scenario
    ))

fig.update_layout(
    title=metric,
    xaxis_title="Date",
    yaxis_title="PCT (%)",
    template="plotly_white"
)

fig.show()
    
```

## 𝄜 Top contraintes du mois

```{python}
#| code-fold: true

df_PM=sq.get_PostMortem(pool_id
                        ,start_date
                        ,end_date
                        ,[f'{market}_1MA_Default', f'{market}_1MA_AvgHistSP', f'{market}_1MA_DL_AvgSP',
                        f'{market}_1DA_Default', f'{market}_1DA_AvgHistSP', f'{market}_1DA_DL_AvgSP',]
                        ,conn)

df_PM.fillna(0,inplace=True)
exclude_columns = ["CID_MAG", "CID_CES", "CONSTRAINTNAME","CONTINGENCYNAME"]

# Apply formatting to all other columns
for col in df_PM.columns:
    if col not in exclude_columns:
        df_PM[col] = df_PM[col].apply(lambda x: f"${x:,}")

# Apply formatting to all other numeric columns


show(df_PM,
    classes="compact",
    column_filters="header", 
    layout={"topEnd": None}, 
    style="font-size: 12px;",
    )


```

```{python}
#| code-fold: true

display("df_PM", df_PM.columns)
df_PM.columns = df_PM.columns.str.replace("'", "")
display("df_PM", df_PM)

def money_to_float(s):
    return (
        s.astype(str)              # <-- ensures .str works
         .str.replace("$", "", regex=False)
         .str.replace(",", "", regex=False)
         .astype(float)
    )

# Convert money columns
df_PM["SP_DA"] = money_to_float(df_PM["SP_DA"])
df_PM["NEPOOL_1MA_Default"] = money_to_float(df_PM["NEPOOL_1MA_Default"])

# True positives = both SP_DA and Default ≠ 0
tp = df_PM[(df_PM["SP_DA"] != 0) & (df_PM["NEPOOL_1MA_Default"] != 0)]

# TP-only average absolute difference
result_tp = abs((tp["SP_DA"].abs() - tp["NEPOOL_1MA_Default"].abs()).mean())

print("1MA_Default (TP only):", result_tp)


```

### Statistiques scénarios Monthly:
- 1MA_Default: 4/6
- 1MA_AvgHistSP: 5/6
- 1MA_DL_AvgSP: 2/6
- La combinaison capte: 5/6

### Statistiques scénarios Daily:
- 1DA_Default: 4/6
- 1DA_AvgHistSP: 4/6
- 1DA_DL_AvgSP: 6/6
- La combinaison capte: 6/6

### Comparaison avec les top contraintes de Yes
```{python}
# | echo: false
display(Image("H:\\GitHub\\Postmortem-NYISO\\PostMortem-NYISO-Quarto\\Novembre 2025 NEPOOL\\TopContraintesDansYesNov2025.png"))
```

## 🕵️ Analyses des contraintes
```{python}
# | echo: false

# paramètres généraux
ftrstartdate=start_date
ftrenddate=end_date
histostartdate=start_date
histoenddate=end_date
scenario_flows=[f'{market}_1MA_Default',f'{market}_1DA_Default',f'{market}_1MA_AvgHistSP', f'{market}_1MA_DL_AvgtSP' ]
scenario_first_priority=f'{market}_1DA_Default'
scenario_sf=[f'{market}_1MA_Default',f'{market}_1DA_Default']
scenario_histo_sp=[f'{market}_1MA_Default',f'{market}_1DA_Default',
                    f'{market}_1MA_AvgHistSP',
                    f'{market}_1MA_DL_AvgtSP'
                    ]
```


<details>
  <summary> BURG </summary>

**Infos :**

- CID_MAG: 30002892
- CID_CES: 1080
- CES_NAME = 'Burgess Generation (BURG)'
- CONTINGENCYNAME: INTERFACE
- La contrainte a bindé tous les jours au RT du 4-25 novembre (le plus était le 23 pour 2387.60$).
- Elle a bindé tous les jours au DAM du 6-26 novembre (le plus était le 12 pour 1190.15$).

**Analyse :**

- Il n'est pas clair dans dayzer pourquoi la contrainte binde, mais c'est probablement dû à la génération du 2087 Burgess BioPower et l'outage de ligne suivant dans le coin aient eu un effet. Les outages étaient présents dans les monthlys et les dailys.

```{python}
# | echo: false
data = [
{
"Source": "NEISO",
"Equipment": "BERLN_NH 115 KV LINE S136: WHITEFLD",
"Type": "LINE",
"KV": 115,
"Start": "11/09/2025 04:49",
"End": "11/26/2025 ...",
"Planned Start": "11/09/2025 04:30",
"Planned End": "11/26/2025 19:00",
},
{
"Source": "NEISO",
"Equipment": "WHITEFLD 115 KV BRKR S1360",
"Type": "LINE",
"KV": 115,
"Start": "11/09/2025 04:49",
"End": "11/26/2025 ...",
"Planned Start": "11/09/2025 04:30",
"Planned End": "11/26/2025 19:00",
},
{
"Source": "NEISO",
"Equipment": "WHITEFLD 115 KV BRKR 03601/03",
"Type": "LINE",
"KV": 115,
"Start": "11/09/2025 04:49",
"End": "11/26/2025 ...",
"Planned Start": "11/09/2025 04:30",
"Planned End": "11/26/2025 19:00",
}
]

df = pd.DataFrame(data)
display(df)
```

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30002892,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```
</details>

<details>
  <summary> IRFM-E </summary>

**Infos :**

- CID_MAG: 30002873
- CID_CES: 1059
- CES_NAME = 'Inner Rumford Export (IRMF-E)'
- CONTINGENCYNAME: INTERFACE
- Elle a bindé en RT du 14-16 (1.66, 1639.34, 798.09), 19-21 (240.89, 60.01, 320.90) et 23-24 (7.83, 109.17) novembre.
- Elle a bindé au DAM le 1 nov (134.68), 15-16 (667.34, 721.06), 19 (198.06), 21 (170.35) et 24 (377.75).

**Analyse :**

- La contrainte semble binder à cause des outages suivants et de la combinaison de la génération non renouvelable (1970 RUMFORD POWER), du vent (RECORD HILL WIND, Saddleback Mountain Wind, Rox Wind, Canton Mountain Wind) et d'hydro (52108 RUMFORD FALLS).
- L'outage suivante pourrait avoir contribué au binde de la contrainte le 1er novembre:

```{python}
# | echo: false
data = [
{
"Source": "NEISO",
"Equipment": "WOODSTCK 115 KV LINE 210: WOODSTCK",
"Type": "LINE",
"KV": 115,
"Start": "10/27/2025 08:40",
"End": "11/07/2025 14:53",
"Planned Start": "10/27/2025 07:30",
"Planned End": "11/07/2025 14:00",
}
]

df = pd.DataFrame(data)
display(df)
```

- Les outages suivants ont possiblement contribué au binde de la contrainte du 14-25 novembre:

```{python}
# | echo: false
data = [
{
"Source": "NEISO",
"Equipment": "RAYMOND 115 KV LINE 209: RAYMOND",
"Type": "LINE",
"KV": 115,
"Start": "11/12/2025 14:08",
"End": "11/25/2025 14:38",
"Planned Start": "11/12/2025 14:08",
"Planned End": "11/25/2025 16:00",
}
]

df = pd.DataFrame(data)
display(df)
```


- L'outage suivante a possiblement contribé au binde de la contrainte le 24 novembre:

```{python}
# | echo: false
data = [
{
"Source": "NEISO",
"Equipment": "LOVELL 115 KV LINE 214-3: LOVELL",
"Type": "LINE",
"KV": 115,
"Start": "11/24/2025 06:50",
"End": "11/26/2025 17:23",
"Planned Start": "11/24/2025 06:00",
"Planned End": "11/26/2025 18:00",
}
]

df = pd.DataFrame(data)
display(df)
```


```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30002873,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```
</details> 


<details>
  <summary> WYMAN_HY215ALN </summary>

**Infos :**

- CID_MAG: 30002480		
- CID_CES: 501212
- CES_NAME = 'WYMAN_HY_215_A_LN:ACTUAL'
- CONTINGENCYNAME: ACTUAL
- Elle a bindé en RT le 3 novembre (265.73).
- Elle a bindé au DAM le 3 (703.33) et 4 (937.34) novembre.

**Analyse :**

- Il a l'outage de circuit breaker suivant dans le coin qui a sûrement causé le binde de la contrainte. Cet outage n'est pas dans dayzer, car il ne modélise pas bien les circuits breakers.

```{python}
# | echo: false
data = [
{
"Source": "NEISO",
"Equipment": "WYMAN_HY 115 KV BRKR K215-1: 215",
"Type": "BRKR",
"KV": 115,
"Start": "11/03/2025 06:36",
"End": "11/04/2025 08:53",
"Planned Start": "11/03/2025 07:00",
"Planned End": "11/05/2025 12:00",
},	
]

df = pd.DataFrame(data)
display(df)


# display(Image("H:\GitHub\Postmortem-NYISO\PostMortem-NYISO-Quarto\Octobre 2025 NEPOOL\ORRINGTN249ALN_20OctAu23Oct.png"))
```

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30002862,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```

</details>

<details>
  <summary> KR-EXP </summary>

**Infos :**

- CID_MAG: 30002862
- CID_CES: 1047
<!-- - MKUNITCID: 25583_1044 -->
- CES_NAME = 'KEENE ROAD EXPORT INTERFACE (KR-EXP)'
- CONTINGENCYNAME: INTERFACE
- Elle a bindé en RT le 1 (1077.97), du 4-6 (1032.46, 14.59, 76.01) et 29 novembre (298.60).
- Elle a bindé au DAM du 1-4 (297.86, 13.71, 198.15, 321.77), le 6 (618.55), 7 (5.89), du 17-18 (145.11, 30.07) et le 29 novembre (8.98).

**Analyse :**

- La contrainte semble avoir bindé à cause de la génération de vent (ROLLINS WIND PLANT, STETSON WIND FARM, et STETSON II WIND FARM) et d'hydro (Greatlakes Millinocket Hydro).

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30002862,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```

</details>


<details>
  <summary> DNEAST </summary>

**Infos :**

- CID_MAG: 30002921		
- CID_CES: 1113
- CES_NAME = 'Down East Export (DNEAST)'
- CONTINGENCYNAME: INTERFACE
- Elle a bindé en RT le 25 (-88.38) et du 27-30 novembre (-100.41, -159.22, -1025.75, -639.79).
- Elle a bindé au DAM du 28-30 novembre (-280.04, -731.51, -398.76).

**Analyse :**

- La contrainte semble avoir bindé à cause de la génération de vent (15673 Downeast Wind, 18033 Weaver Wind Maine, 18026 Hancock Wind ME, 18018 BULL HILL WIND).

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30002921,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```

</details> 
 

<details>
  <summary> KCW </summary>

**Infos :**

- CID_MAG: 30002880
- CID_CES: 1066
<!-- - MKUNITCID: 25583_1044 -->
- CES_NAME = 'Kingdom Wind Generation (KCW)'
- CONTINGENCYNAME: INTERFACE
- Elle a surtout bindé en RT du 3-4 (-104.45, -782.04) et du 5-9 (-3.26, -22.08, -48.01, -89.01) novembre.
- Elle a bindé au DAM du 3-4 (-236.97, -467.16) et du 6-7 (-362.00, -236.96) novembre.

**Analyse :**

- Du 3 au 5 novembre, il avait les outages suivants dans le coin. KCW est une contrainte qui est connue pour binder à cause d'outages.

```{python}
# | echo: false
data = [
{
"Source": "NEISO",
"Equipment": "CONVERTR 115 KV BRKR N_B1_1",
"Type": "BRKR",
"KV": 115,
"Start": "11/04/2025 22:36",
"End": "11/05/2025 02:53",
"Planned Start": "11/04/2025 22:36",
"Planned End": "11/05/2025 23:59",
},
{
"Source": "NEISO",
"Equipment": "CONVERTR 120 KV LINE 1429: CONVERTR",
"Type": "LINE",
"KV": 115,
"Start": "11/04/2025 22:36",
"End": "11/05/2025 02:53",
"Planned Start": "11/04/2025 22:36",
"Planned End": "11/05/2025 23:59",
},
{
"Source": "NEISO",
"Equipment": "CONVERTR 115 KV BRKR N_B1_2",
"Type": "BRKR",
"KV": 115,
"Start": "11/04/2025 22:36",
"End": "11/05/2025 02:53",
"Planned Start": "11/04/2025 22:36",
"Planned End": "11/05/2025 23:59",
},
{
"Source": "NEISO",
"Equipment": "SO_HERO 115 KV LINE PV20-1: SO_HERO",
"Type": "LINE",
"KV": 115,
"Start": "11/03/2025 06:59",
"End": "11/14/2025 17:53",
"Planned Start": "11/03/2025 06:00:00",
"Planned End": "11/14/2025 18:00:00",
}
]

df = pd.DataFrame(data)
display(df)


display(Image("H:\\GitHub\\Postmortem-NYISO\\PostMortem-NYISO-Quarto\\Novembre 2025 NEPOOL\\KCW_3-4Nov.png"))
```

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30002880,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```
</details> 


<details>
  <summary> STRA </summary>

**Infos :**

- CID_MAG: 30002928
- CID_CES: 1120
- CES_NAME = 'Reenergy Stratton Generation (STRA)'
- CONTINGENCYNAME: INTERFACE
- Il manquait le mapping entre la contrainte dans Dayzer et dans Yes, donc on l'a ajouté.
- La contrainte a bindé en RT du 5-6 (-54.25, -14.59) et 10-13 (-159.93, -63.36, -6.16, -62.39) novembre.
- La contrainte a bindé au DAM en septembre pour -56.40. En octobre, elle a bindé pour -889.52 en RT et -1225.63 au DAM. En novembre, elle a bindé au DAM le 5-7 (-131.90, -171.96, -107.26) et 13 (-552.40).


**Analyse :**

- La contrainte semble binder à cause de la production non renouvelable (REENERGY STRATTON).
- L'outage suivant a peut-être contribué à le binde de la contrainte.

```{python}
# | echo: false
data = [
{
"Source": "NEISO",
"Equipment": "WYMAN_HY 115 KV LINE 63-1",
"Type": "LINE",
"KV": 115,
"Start": "11/12/2025 07:35",
"End": "11/13/2025 14:23",
"Planned Start": "11/12/2025 07:00",
"Planned End": "11/13/2025 16:00",
}
]

df = pd.DataFrame(data)
display(df)


display(Image("H:\\GitHub\\Postmortem-NYISO\\PostMortem-NYISO-Quarto\\Novembre 2025 NEPOOL\\STRA_12-15Nov.png"))
```

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30002928,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```
</details>

<details>
  <summary> BUNKR_HL1029-2ALN  </summary>

**Infos :**

- CID_MAG: 30001083
- CID_CES: 611255
- CES_NAME = 'BUNKR_HL_1029-2_A_LN:1789'
- CONTINGENCYNAME: 1789
- Elle a bindé en RT le 19-21 (-94.22, -69.25, -1318.97), 23 (-420.98) et 25 (-56.62) novembre.
- Elle a bindé au DAM du 20-21 (-28.41, -196.04) et 23-25 (-298.57, -188.31, -51.29) novembre.


**Analyse :**

- La monitored line associée à la contrainte est en outage du 5 octobre au 5 novembre.
- La contrainte semble binder à cause des outages 2326 BEACN_FL ~115KV-OXFORD ~115KV-1 (qui dure du 27 octobre au 26 novembre, eqkey 1319) et 2322 S_NAUGTK ~115KV-TOWANTIC (7-26 novembre, eqkey 1142) de même que la génération de l'unité 225 CPC Towantic. Cette dernière était prévue de possiblement être en outage, mais ça ne semble pas avoir été le cas. Elle a donc généré et contribué au binde de la contrainte.
- De manière générale, la contrainte va binder à cause d'outages et la génération de l'unité 225 CPC Towantic. Si l'unité CPC Towantic est en outage, il n'a aucune manière que la contrainte binde.

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30001083,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```
</details>

## 𝄜 Retour sur les contraintes du pré-bid
```{python}
# | echo: false

data = [
    {
        "CID_CES": 611255,
        "Nom": "BUNKR_HL_1029-2_A_LN:1789",
        "Binde": "Oui, -1960.04$ au RT et -762.62$ au DAM",
        "Potentiel":"1/5",
        "Outage": (
              " Oui, 1) Ligne: STEVENSN 115 KV LINE 1232, Du 6 au 13 nov (Interim Approved);"
              " Oui, 2) Ligne: BEACN_FL 115 KV LINE 1319, du 27 oct au 26 nov (Interim Approved);"
              " Oui, 3) Ligne: S_NAUGTK 115 KV LINE 1142, du 19 oct au 26 novembre (Interim Approved);"
              " Non, A) Unité: CPV TOWANTIC, du 10 oct au 9 novembre"
        ),
    },
    {
        "CID_CES": 1113,
        "Nom": "Down East Export (DNEAST)",
        "Binde": "Oui, -2013.55$ au RT et -1410.31$ au DAM pour le mois.",
        "Potentiel":"2.5/5",
        "Outage": "",
    },
    {
        "CID_CES": 1132,
        "Nom": "Down East Wind Generation (DNEW)",
        "Binde": "Non",
        "Potentiel":"2.5/5",
        "Outage": "",
    },
    {
        "CID_CES": 611264,
        "Nom": "EPPING_T_59BHE-2_A_LN:51BHE",
        "Binde": "Oui, -5.37$ au DAM pour le mois.",
        "Potentiel":"2.5/5",
        "Outage": "",
    },
    {
        "CID_CES": 501174,
        "Nom": "FRSTBRDG_1445_A_LN:1340",
        "Binde": "Non",
        "Potentiel":"1/5",
        "Outage": "",
    },
    {
        "CID_CES": 610094,
        "Nom": "GRAHAM_66BHE_A_LN:205",
        "Binde": "Oui, -232.79$ au RT et -191.12$ au DAM pour le mois.",
        "Potentiel":"2.5/5",
        "Outage": "",
    },
    {
        "CID_CES": 22000048,
        "Nom": "NORWALKH_602_A_LN:ACTUAL",
        "Binde": "Non",
        "Potentiel":"0.5/5",
        "Outage": (
              " Oui, 1) Ligne: CRKT_VLY 345 KV LINE NY-Y17CD, du 1er au 21 novembre (Interim Approved);"
              " Non, A) Unité: CPV TOWANTIC, du 10 oct au 9 novembre"
        ),
    },
    {
        "CID_CES": 22000047,
        "Nom": "NORWALKH_603_A_LN:ACTUAL",
        "Binde": "Non",
        "Potentiel":"0.5/5",
        "Outage": (
              " Oui, 1) Ligne: CRKT_VLY 345 KV LINE NY-Y17CD, du 1er au 21 novembre (Interim Approved);"
              " Non, A) Unité: CPV TOWANTIC, du 10 oct au 9 novembre"
        ),
    },
    {
        "CID_CES": 501284,
        "Nom": "SALISBRY_690/FV_A_LN:ACTUAL",
        "Binde": "Oui, -3771.96$ au DAM pour le mois.",
        "Potentiel":"2/5",
        "Outage": (
              " Oui, 1) Ligne: CRKT_VLY 345 KV LINE NY-Y17CD, du 1er au 21 novembre (Interim Approved);"
              " Non, A) Unité: CPV TOWANTIC, du 10 oct au 9 novembre"
        ),
    },
    {
        "CID_CES": 1055,
        "Nom": "WHITEFIELD SOUTH & GRPW (WTS+GR)",
        "Binde": "Non",
        "Potentiel":"1/5",
        "Outage": "LITTLETN 115 KV LINE U199, du 27 oct au 8 nov (Interim Approved)",
    },
    {
        "CID_CES": 1080,
        "Nom": "Burgess Generation (BURG)",
        "Binde": "Oui, -15251.69$ en RT et -14037.50$ au DAM pour le mois.",
        "Potentiel":"3/5",
        "Outage": "BERLN_NH 115 KV LINE S136: WHITEFLD, du 9 au 26 nov (Interim Approved)"
    }
]

df = pd.DataFrame(data)
# df

from itables import show
import itables.options as opt

opt.maxBytes = 0  # allow long cells
opt.lengthMenu = [10, 25, 50, 100]

show(df)

```
</details>


 


