---
title: "Postmortem NEPOOL Décembre 2025"
author: "Nicolas Leblanc"
date: today
toc: true
jupyter: python3
format:
  html:
    embed-resources: true
    code-tools: true
    grid:
    #   margin-width: 0px  # Reduces side margins
      body-width: 1400px  # Adjusts main content width (default is ~800px)
execute:
  echo: true  # Keep code visible by default
  code-tools: true  # Add show/hide button for each code block

---

## 🛠️ Points à discuter et Projets

- Application des prébis, accessible via l'url : https://bidanalysis.magitdev.com/.


<!-- Importation des librairies et initalisation de la connection -->
```{python}
#| code-fold: true
# Import necessary libraries
from services import snowflake_queries as sq
from components import graph_utils as gu, constraint_utils as cu
import plotly.graph_objects as go
from services.database_connection import init_connection
from itables import show, JavascriptFunction
import ipywidgets as widgets
from IPython.display import Image, display
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import plotly.express as px
import plotly.graph_objects as go
from metriques.histogram_AvgAbsErrContribution import money_to_float, compute_tp_diff, plot_constraint_percent

conn=init_connection()
```

## 📈 Evolution de la load et du vents
<!-- - La LoadMin est plus adapté au début du mois, le LoadMax l'est plus vers la fin du mois.
- Au début (1-7 septembre) et à la fin du mois (22-30 septembre) la différence entre le daily et le monthly (8-21 septembre) est plus petit qu'au milieu du mois. -->
- La génération totale est cyclique.

```{python}
# | code-fold: true
market = 'NEPOOL'
start_date = '2025-12-01'
end_date = '2025-12-31'
pool_id = 3
df_Load=sq.get_Load([f'{market}_1DA_Default', f'{market}_1MA_Default', f'{market}_1MA_LoadMin',f'{market}_1MA_LoadMax']
                  ,'2020-01-01'
                  ,end_date
                  ,conn
                  )
```

- La génération de vent n'est pas cyclique.
<!-- - Le monthly et le daily pour le vent sont similaieres au scénario WindMin au milieu du mois, mais ils diffèrent pour le reste du mois (11-20 septembre). -->

```{python}
# | code-fold: true
df_Wind=sq.get_Wind([f'{market}_1DA_Default',f'{market}_1MA_Default',f'{market}_1MA_WindMin',f'{market}_1MA_WindMax']
                  ,'2020-01-01'
                  ,end_date
                  ,conn
                  )

gu.create_graph_load(df_Load,'TOTAL',start_date,end_date)
gu.create_graph_wind(df_Wind,start_date,end_date)
```

## Métriques

```{python}
# | echo: false

query = f"""
SELECT *
FROM TABLE(
    MAGSNOWFLAKE.DAYZER.FN_METRICS_MONTHLY(
        3,
        ARRAY_CONSTRUCT('NEPOOL_1MA_AvgHistSP','NEPOOL_1MA_Default','NEPOOL_1MA_DL_AvgSP'),
        DATE('2024-04-01'),
        DATE('{end_date}'),
        50
    )
)
"""

df_metriques = pd.read_sql(query, conn)

metrics = [
    "PCT_CAPTE_DU_SP_TOTAL_CUTOFF",
    "PCT_FP_SUP_CUTOFF_DZR",
    "AVG_ERR_ABS_TP"
]

scenarios = [
    "NEPOOL_1MA_AvgHistSP",
    "NEPOOL_1MA_Default",
    "NEPOOL_1MA_DL_AvgSP"
]

df_metriques = df_metriques[df_metriques["SCENARIONAME"].isin(scenarios)]


```

### PCT_CAPTE_DU_SP_TOTAL_CUTOFF

- Pourcentage du SP capté par scénario (CUTOFF 50$): uniquement pour les contraintes captées par Dayzer et qui ont bindé dans le marché, par rapport au SP total du marché
- 100*SUM(ABS(SP_MKT) uniquement celle captées par Dayzer et dont le SP_DZR est supérieur au CutOff)/SUM(ABS(SP_MKT de toutes les contraintes) )

```{python}
# | echo: false

metric = "PCT_CAPTE_DU_SP_TOTAL_CUTOFF"

# plt.figure(figsize=(12, 6))

# for scenario in scenarios:
#     temp = df_metriques[df_metriques["SCENARIONAME"] == scenario]
#     plt.plot(temp["FTRDATE"], temp[metric], label=scenario)

# plt.title(metric)
# plt.xlabel("Date", fontsize=14, fontweight="bold", labelpad=15)
# plt.ylabel("PCT (%)", fontsize=14, fontweight="bold", labelpad=15)
# plt.legend()
# plt.grid(True)
# ax = plt.gca()
# ax.xaxis.set_major_locator(mdates.MonthLocator())
# ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
# plt.xticks(rotation=45)
# plt.show()

fig = go.Figure()

for scenario in scenarios:
    temp = df_metriques[df_metriques["SCENARIONAME"] == scenario]
    fig.add_trace(go.Scatter(
        x=temp["FTRDATE"],
        y=temp[metric],
        mode="lines",
        name=scenario
    ))

fig.update_layout(
    title=metric,
    xaxis_title="Date",
    yaxis_title="PCT (%)",
    template="plotly_white"
)

fig.show()
    
```

### PCT_FP_SUP_CUTOFF_DZR

- Pourcentage des faux positifs: Nombre des contraintes qui bindent dans Dayzer et qui ne bindent pas dans le marché, divisé par le nombre total de contrainte qui bindent dans Dayzer avec ABS(SP_DZR) >= CutOff (=50$)

```{python}
# | echo: false

metric = "PCT_FP_SUP_CUTOFF_DZR"

# plt.figure(figsize=(12, 6))

# for scenario in scenarios:
#     temp = df_metriques[df_metriques["SCENARIONAME"] == scenario]
#     plt.plot(temp["FTRDATE"], temp[metric], label=scenario)

# plt.title(metric)
# plt.xlabel("Date", fontsize=14, fontweight="bold", labelpad=15)
# plt.ylabel("PCT (%)", fontsize=14, fontweight="bold", labelpad=15)
# plt.legend()
# plt.grid(True)
# ax = plt.gca()
# ax.xaxis.set_major_locator(mdates.MonthLocator())
# ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
# plt.xticks(rotation=45)
# plt.show()

fig = go.Figure()

for scenario in scenarios:
    temp = df_metriques[df_metriques["SCENARIONAME"] == scenario]
    fig.add_trace(go.Scatter(
        x=temp["FTRDATE"],
        y=temp[metric],
        mode="lines",
        name=scenario
    ))

fig.update_layout(
    title=metric,
    xaxis_title="Date",
    yaxis_title="PCT (%)",
    template="plotly_white"
)

fig.show()

```

### AVG_ERR_ABS_TP

- Moyenne des erreurs absolues pour les vrais positifs: AVG(ABS(ABS(SP_MKT)-ABS(SP_DZR)))

```{python}
# | echo: false

metric = "AVG_ERR_ABS_TP"

# plt.figure(figsize=(12, 6))

# for scenario in scenarios:
#     temp = df_metriques[df_metriques["SCENARIONAME"] == scenario]
#     plt.plot(temp["FTRDATE"], temp[metric], label=scenario)

# plt.title(metric)
# plt.xlabel("Date", fontsize=14, fontweight="bold", labelpad=15)
# plt.ylabel("PCT (%)", fontsize=14, fontweight="bold", labelpad=15)
# plt.legend()
# plt.grid(True)
# ax = plt.gca()
# ax.xaxis.set_major_locator(mdates.MonthLocator())
# ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
# plt.xticks(rotation=45)
# plt.show()

fig = go.Figure()

for scenario in scenarios:
    temp = df_metriques[df_metriques["SCENARIONAME"] == scenario]
    fig.add_trace(go.Scatter(
        x=temp["FTRDATE"],
        y=temp[metric],
        mode="lines",
        name=scenario
    ))

fig.update_layout(
    title=metric,
    xaxis_title="Date",
    yaxis_title="PCT (%)",
    template="plotly_white"
)

fig.show()
    
```

- Contribution de chaque contrainte étant un TP pour chaque scénario de ce mois-ci

```{python}
#| code-fold: true

df_PM=sq.get_PostMortem(pool_id
                        ,start_date
                        ,end_date
                        ,[f'{market}_1MA_Default', f'{market}_1MA_AvgHistSP', f'{market}_1MA_DL_AvgSP',
                        f'{market}_1DA_Default', f'{market}_1DA_AvgHistSP', f'{market}_1DA_DL_AvgSP',]
                        ,conn)

df_PM.fillna(0,inplace=True)
exclude_columns = ["CID_MAG", "CID_CES", "CONSTRAINTNAME","CONTINGENCYNAME"]

# Apply formatting to all other columns
for col in df_PM.columns:
    if col not in exclude_columns:
        df_PM[col] = df_PM[col].apply(lambda x: f"${x:,}")

constraint_col = "CONSTRAINTNAME"

df_PM.columns = df_PM.columns.str.replace("'", "")

# 1) Default
tp_default = compute_tp_diff(df_PM, "SP_DA", "NEPOOL_1MA_Default")
plot_constraint_percent(tp_default, constraint_col, "NEPOOL_1MA_Default")

# 2) AvgHistSP scenario
tp_avgHist = compute_tp_diff(df_PM, "SP_DA", "NEPOOL_1MA_AvgHistSP")
plot_constraint_percent(tp_avgHist, constraint_col, "NEPOOL_1MA_AvgHistSP")

# 3) DL_AvgSP scenario
tp_dl_avgSP = compute_tp_diff(df_PM, "SP_DA", "NEPOOL_1MA_DL_AvgSP")
plot_constraint_percent(tp_dl_avgSP, constraint_col, "NEPOOL_1MA_DL_AvgSP")


```

## 𝄜 Top contraintes du mois

```{python}
#| code-fold: true

# df_PM=sq.get_PostMortem(pool_id
#                         ,start_date
#                         ,end_date
#                         ,[f'{market}_1MA_Default', f'{market}_1MA_AvgHistSP', f'{market}_1MA_DL_AvgSP',
#                         f'{market}_1DA_Default', f'{market}_1DA_AvgHistSP', f'{market}_1DA_DL_AvgSP',]
#                         ,conn)

# df_PM.fillna(0,inplace=True)
# exclude_columns = ["CID_MAG", "CID_CES", "CONSTRAINTNAME","CONTINGENCYNAME"]

# # Apply formatting to all other columns
# for col in df_PM.columns:
#     if col not in exclude_columns:
#         df_PM[col] = df_PM[col].apply(lambda x: f"${x:,}")

# Apply formatting to all other numeric columns


show(df_PM,
    classes="compact",
    column_filters="header", 
    layout={"topEnd": None}, 
    style="font-size: 12px;",
    )


```


### Contraintes manquantes et contrainte en double

- Voir le fichier txt et excel, qui se situent au path H:\, contenant les informations sur ces contraintes manquantes pour les ajouter à dayzer et leur mappaing à la BD éventuellement: "Dec 2025 - NEPOOL contraintes manquantes et doublon contrainte".

```{python}
# | echo: false
data = [
{
"Nom": "CANAL1",
"Contingence": "INTERFACE"
},
{
"Nom": "HARTF_AVE105ALN",
"Contingence": "10CC"
},
{
"Nom": "SALEMT146E-1ALN",
"Contingence": "ACTUAL"
},
{
"Nom": "HARTF_AVE105ALN",
"Contingence": "FRNKL10A"
},
{
"Nom": "SHAWS_HL1272ALN",
"Contingence": "FRSTB28T"
},
{
"Nom": "FRSTBRDG1445ALN",
"Contingence": "FRSTB28T"
},
{
"Nom": "HARTF_AVF106ALN",
"Contingence": "FRNKE105"
},
{
"Nom": "BEARSWMPE205WALN",
"Contingence": "ZB62"
},
{
"Nom": "CANAL",
"Contingence": "INTERFACE"
},
{
"Nom": "FRSTBRDG1445ALN",
"Contingence": "1340"
},
{
"Nom": "BEARSWMPE205WALN",
"Contingence": "393"
},
{
"Nom": "WEINGART1732-3ALN",
"Contingence": "ZB69"
},
{
"Nom": "BAKER_ST110D110DXF",
"Contingence": "ACTUAL"
},
{
"Nom": "BAKER_ST110C110CXF",
"Contingence": "ACTUAL"
},
{
"Nom": "WALTHAM282-521-2ALN",
"Contingence": "ACTUAL"
},
]

df = pd.DataFrame(data)
display(df)
```

- Il semble avoir un doublon de la contrainte NS_ST de contingence INTERFACE. Il a les CID_MAG 30002842 et 30002841, puis les CID_CES 1025 et 1024.

### Statistiques scénarios Monthly:
- 1MA_Default: /6
- 1MA_AvgHistSP: /6
- 1MA_DL_AvgSP: /6
- La combinaison capte: /6

### Statistiques scénarios Daily:
- 1DA_Default: /6
- 1DA_AvgHistSP: /6
- 1DA_DL_AvgSP: /6
- La combinaison capte: /6

### Comparaison avec les top contraintes de Yes
```{python}
# | echo: false
display(Image("H:\\GitHub\\Postmortem-NYISO\\PostMortem-NYISO-Quarto\\Novembre 2025 NEPOOL\\TopContraintesDansYesNov2025.png"))
```

## 🕵️ Analyses des contraintes
```{python}
# | echo: false

# paramètres généraux
ftrstartdate=start_date
ftrenddate=end_date
histostartdate=start_date
histoenddate=end_date
scenario_flows=[f'{market}_1MA_Default',f'{market}_1DA_Default',f'{market}_1MA_AvgHistSP', f'{market}_1MA_DL_AvgtSP' ]
scenario_first_priority=f'{market}_1DA_Default'
scenario_sf=[f'{market}_1MA_Default',f'{market}_1DA_Default']
scenario_histo_sp=[f'{market}_1MA_Default',f'{market}_1DA_Default',
                    f'{market}_1MA_AvgHistSP',
                    f'{market}_1MA_DL_AvgtSP'
                    ]
```

<details>
  <summary> BERLN1771ALN </summary>

**Infos :**

- CID_MAG: 30000951
- CID_CES: 611104
- CES_NAME = 'BERLN1771ALN:ZB16'
- CONTINGENCYNAME: ZB16
- En RT, la contrainte n'a pas bindé.
- Au DAM, elle a bindé du 2-3 (800.13, 898.00), 5-11 (4301.99, 5089.04, 11084.44, 12993.27, 8546.39, 3587.83, 1955.14) ... décembre.

**Analyse :**

- La génération non renouvelable semble avoir contribué au binde de la contrainte.
- L'outage suivant semble aussi avoir eu un effet.
```{python}
# | echo: false
data = [
{
"Source": "NEISO",
"Equipment": "N_BLOOM 345 KV LINE 3642",
"Type": "LINE",
"KV": 115,
"Start": "12/05/2025 17:49",
"End": "12/10/2025 11:56",
"Planned Start": "12/05/2025 18:01",
"Planned End": "12/10/2025 13:00",
}
]

df = pd.DataFrame(data)
display(df)
```

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30000951,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```
</details>

<details>
  <summary> DNEAST </summary>

**Infos :**

- CID_MAG: 30002921		
- CID_CES: 1113
- CES_NAME = 'Down East Export (DNEAST)'
- CONTINGENCYNAME: INTERFACE
- En RT, la contrainte a bindé le 1 (799.56), du 2-5 (1138.16, 1701.19, 947.33), 7-11 (762.35, 2325.62, 214.31, 927.55, 19.54) ... décembre.
- Au DAM, elle a bindé du 1-5 (329.58, 88.60, 571.44, 671.49, 217.53), le 8 (1152.28), du 10-12 (637.08, 3214.75, 3021.53) ... décembre.

**Analyse :**

- La contrainte semble avoir bindé à cause de la génération de vent (15673 Downeast Wind, 18033 Weaver Wind Maine, 18026 Hancock Wind ME, 18018 BULL HILL WIND).

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30002921,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```

</details> 

<details>
  <summary> BURG </summary>

**Infos :**

- CID_MAG: 30002892
- CID_CES: 1080
- CES_NAME = 'Burgess Generation (BURG)'
- CONTINGENCYNAME: INTERFACE
- En RT, la contrainte a bindé le 5 (2418.64), 12 (153.04) ... décembre.
- Au DAM, elle a bindé le 5 (2903.75), 12 (870.90) ... décembre.

**Analyse :**

- Il n'est pas clair dans dayzer pourquoi la contrainte binde, mais c'est probablement dû à la génération du 2087 Burgess BioPower et l'outage de ligne suivant dans le coin, qui est présent trois jours (5, 12, 19) décembre. On ne voit pas l'effet de l'outage dans nos simulations.

```{python}
# | echo: false
data = [
{
"Source": "NEISO",
"Equipment": "BERLN_NH 115 KV LINE S136: WHITEFLD",
"Type": "LINE",
"KV": 115,
"Start": "12/05/2025 04:35",
"End": "12/05/2025 17:53",
"Planned Start": "12/05/2025 04:30",
"Planned End": "12/05/2025 19:00",
},
{
"Source": "NEISO",
"Equipment": "BERLN_NH 115 KV LINE S136: WHITEFLD",
"Type": "LINE",
"KV": 115,
"Start": "12/12/2025 04:35",
"End": "12/12/2025 17:53",
"Planned Start": "12/12/2025 04:30",
"Planned End": "12/12/2025 19:00",
},
{
"Source": "NEISO",
"Equipment": "BERLN_NH 115 KV LINE S136: WHITEFLD",
"Type": "LINE",
"KV": 115,
"Start": "12/19/2025 04:35",
"End": "12/19/2025 17:53",
"Planned Start": "12/19/2025 04:30",
"Planned End": "12/19/2025 19:00",
}
]

df = pd.DataFrame(data)
display(df)
```

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30002892,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```
</details>

<details>
  <summary> KR-EXP </summary>

**Infos :**

- CID_MAG: 30002862
- CID_CES: 1047
- CES_NAME = 'KEENE ROAD EXPORT INTERFACE (KR-EXP)'
- CONTINGENCYNAME: INTERFACE
- En RT, la contrainte a bindé le 1 (477.32), 4 (1236.49), 12 (2284.20) ... décembre.
- Au DAM, elle a bindé le 1 (110.27), 4 (43.34), du 11-12 (624.51, 2568.88)... décembre.

**Analyse :**

- La contrainte semble avoir bindé à cause de la génération de vent (ROLLINS WIND PLANT, STETSON WIND FARM, et STETSON II WIND FARM) et d'hydro (Greatlakes Millinocket Hydro).

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30002862,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```

</details>

<details>
  <summary> IRFM-E </summary>

**Infos :**

- CID_MAG: 30002873
- CID_CES: 1059
- CES_NAME = 'Inner Rumford Export (IRMF-E)'
- CONTINGENCYNAME: INTERFACE
- En RT, la contrainte a bindé le 1 (871.47), du 7-9 (83.26, 512.70, 201.06), 11-12 (342.33, 40.92) décembre.
- Au DAM, elle a bindé le 1 (267.06), 5 (1466.87), du 8-9 (665.31, 18.76), 11-12 (435.93, 2.92) ... décembre.

**Analyse :**

- La contrainte semble binder à cause des outages suivants et de la combinaison de la génération non renouvelable (1970 RUMFORD POWER), du vent (RECORD HILL WIND, Saddleback Mountain Wind, Rox Wind, Canton Mountain Wind) et d'hydro (52108 RUMFORD FALLS).

- Les outages suivant pourraient avoir contribué au binde de la contrainte du 1-5 décembre.

```{python}
# | echo: false
data = [
{
"Source": "NEISO",
"Equipment": "WYMAN_HY 115 KV LINE 63-1",
"Type": "LINE",
"KV": 115,
"Start": "12/01/2025 06:19",
"End": "12/03/2025 15:08",
"Planned Start": "12/01/2025 06:00",
"Planned End": "12/03/2025 16:00",
},
{
"Source": "NEISO",
"Equipment": "STARKS 115 KV LINE 63-2",
"Type": "LINE",
"KV": 115,
"Start": "12/04/2025 07:46",
"End": "12/05/2025 13:53",
"Planned Start": "12/04/2025 06:00",
"Planned End": "12/05/2025 16:00",
},
{
"Source": "NEISO",
"Equipment": "LOVELL 115 KV LINE 214-3: LOVELL",
"Type": "LINE",
"KV": 115,
"Start": "12/01/2025 08:14",
"End": "12/01/2025 18:53",
"Planned Start": "12/01/2025 06:00",
"Planned End": "12/05/2025 18:00",
},
{
"Source": "NEISO",
"Equipment": "LOVELL 115 KV LINE 214-3: LOVELL",
"Type": "LINE",
"KV": 115,
"Start": "12/03/2025 08:21",
"End": "12/04/2025 16:38",
"Planned Start": "12/03/2025 06:00",
"Planned End": "12/05/2025 18:00",
}
]

df = pd.DataFrame(data)
display(df)
```

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30002873,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```
</details> 


<details>
  <summary> SHAWS_HL1272ALN </summary>

**Infos :**

- CID_MAG: 30001155		
- CID_CES: 611330
- CES_NAME = 'SHAWS_HL1272ALN:1340'
- CONTINGENCYNAME: 1340
- En RT, la contrainte n'a pas bindé en décembre.
- Au DAM, elle a bindé du 8-12 (225.41, 94.23, 382.99, 882.80, 409.01) ... décembre.

**Analyse :**

- La génération non-renouvelable (225 CPV Towantic, 1758 Bridgeport NCC, 1821 BRIDGEPORT ENERGY 1, 1775 MILFORD POWER 2, 1774 MILFORD POWER 1) met de la pression.
- Les outages suivants créent de la congestion:		

```{python}
# | echo: false
data = [
{
"Source": "NEISO",
"Equipment": "BESECK 345 KV LINE 3827: BESECK",
"Type": "LINE",
"KV": 115,
"Start": "12/01/2025 13:17",
"End": "12/.../2025 ...:...",
"Planned Start": "12/01/2025 08:00",
"Planned End": "11/12/2025 16:00",
},
{
"Source": "NEISO",
"Equipment": "OXFORD 115 KV LINE 1403",
"Type": "LINE",
"KV": 115,
"Start": "12/07/2025 20:58",
"End": "12/.../2025 ...:...",
"Planned Start": "12/08/2025 01:00",
"Planned End": "12/15/2025 10:30",
},
{
"Source": "NEISO",
"Equipment": "FRSTBRDG 115 KV LINE 1721: FRSTBRDG",
"Type": "LINE",
"KV": 115,
"Start": "12/07/2025 22:54",
"End": "12/08/2025 ...:...",
"Planned Start": "12/08/2025 01:00",
"Planned End": "12/15/2025 10:30",
},

]

df = pd.DataFrame(data)
display(df)


# display(Image("H:\GitHub\Postmortem-NYISO\PostMortem-NYISO-Quarto\Octobre 2025 NEPOOL\ORRINGTN249ALN_20OctAu23Oct.png"))
```

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30002862,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```

</details>





 

<details>
  <summary> KCW </summary>

**Infos :**

- CID_MAG: 30002880
- CID_CES: 1066
<!-- - MKUNITCID: 25583_1044 -->
- CES_NAME = 'Kingdom Wind Generation (KCW)'
- CONTINGENCYNAME: INTERFACE
- Elle a surtout bindé en RT du 3-4 (-104.45, -782.04) et du 5-9 (-3.26, -22.08, -48.01, -89.01) novembre.
- Elle a bindé au DAM du 3-4 (-236.97, -467.16) et du 6-7 (-362.00, -236.96) novembre.

**Analyse :**

- Du 3 au 5 novembre, il avait les outages suivants dans le coin. KCW est une contrainte qui est connue pour binder à cause d'outages.

```{python}
# | echo: false
data = [
{
"Source": "NEISO",
"Equipment": "CONVERTR 115 KV BRKR N_B1_1",
"Type": "BRKR",
"KV": 115,
"Start": "11/04/2025 22:36",
"End": "11/05/2025 02:53",
"Planned Start": "11/04/2025 22:36",
"Planned End": "11/05/2025 23:59",
},
{
"Source": "NEISO",
"Equipment": "CONVERTR 120 KV LINE 1429: CONVERTR",
"Type": "LINE",
"KV": 115,
"Start": "11/04/2025 22:36",
"End": "11/05/2025 02:53",
"Planned Start": "11/04/2025 22:36",
"Planned End": "11/05/2025 23:59",
},
{
"Source": "NEISO",
"Equipment": "CONVERTR 115 KV BRKR N_B1_2",
"Type": "BRKR",
"KV": 115,
"Start": "11/04/2025 22:36",
"End": "11/05/2025 02:53",
"Planned Start": "11/04/2025 22:36",
"Planned End": "11/05/2025 23:59",
},
{
"Source": "NEISO",
"Equipment": "SO_HERO 115 KV LINE PV20-1: SO_HERO",
"Type": "LINE",
"KV": 115,
"Start": "11/03/2025 06:59",
"End": "11/14/2025 17:53",
"Planned Start": "11/03/2025 06:00:00",
"Planned End": "11/14/2025 18:00:00",
}
]

df = pd.DataFrame(data)
display(df)


display(Image("H:\\GitHub\\Postmortem-NYISO\\PostMortem-NYISO-Quarto\\Novembre 2025 NEPOOL\\KCW_3-4Nov.png"))
```

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30002880,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```
</details> 


<details>
  <summary> STRA </summary>

**Infos :**

- CID_MAG: 30002928
- CID_CES: 1120
- CES_NAME = 'Reenergy Stratton Generation (STRA)'
- CONTINGENCYNAME: INTERFACE
- Il manquait le mapping entre la contrainte dans Dayzer et dans Yes, donc on l'a ajouté.
- La contrainte a bindé en RT du 5-6 (-54.25, -14.59) et 10-13 (-159.93, -63.36, -6.16, -62.39) novembre.
- La contrainte a bindé au DAM en septembre pour -56.40. En octobre, elle a bindé pour -889.52 en RT et -1225.63 au DAM. En novembre, elle a bindé au DAM le 5-7 (-131.90, -171.96, -107.26) et 13 (-552.40).


**Analyse :**

- La contrainte semble binder à cause de la production non renouvelable (REENERGY STRATTON).
- L'outage suivant a peut-être contribué à le binde de la contrainte.

```{python}
# | echo: false
data = [
{
"Source": "NEISO",
"Equipment": "WYMAN_HY 115 KV LINE 63-1",
"Type": "LINE",
"KV": 115,
"Start": "11/12/2025 07:35",
"End": "11/13/2025 14:23",
"Planned Start": "11/12/2025 07:00",
"Planned End": "11/13/2025 16:00",
}
]

df = pd.DataFrame(data)
display(df)


display(Image("H:\\GitHub\\Postmortem-NYISO\\PostMortem-NYISO-Quarto\\Novembre 2025 NEPOOL\\STRA_12-15Nov.png"))
```

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30002928,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```
</details>

<details>
  <summary> BUNKR_HL1029-2ALN  </summary>

**Infos :**

- CID_MAG: 30001083
- CID_CES: 611255
- CES_NAME = 'BUNKR_HL_1029-2_A_LN:1789'
- CONTINGENCYNAME: 1789
- Elle a bindé en RT le 19-21 (-94.22, -69.25, -1318.97), 23 (-420.98) et 25 (-56.62) novembre.
- Elle a bindé au DAM du 20-21 (-28.41, -196.04) et 23-25 (-298.57, -188.31, -51.29) novembre.


**Analyse :**

- La monitored line associée à la contrainte est en outage du 5 octobre au 5 novembre.
- La contrainte semble binder à cause des outages 2326 BEACN_FL ~115KV-OXFORD ~115KV-1 (qui dure du 27 octobre au 26 novembre, eqkey 1319) et 2322 S_NAUGTK ~115KV-TOWANTIC (7-26 novembre, eqkey 1142) de même que la génération de l'unité 225 CPC Towantic. Cette dernière était prévue de possiblement être en outage, mais ça ne semble pas avoir été le cas. Elle a donc généré et contribué au binde de la contrainte.
- De manière générale, la contrainte va binder à cause d'outages et la génération de l'unité 225 CPC Towantic. Si l'unité CPC Towantic est en outage, il n'a aucune manière que la contrainte binde.

```{python}
# | echo: false

cu.get_all_cstr_data(pool_id,
                      30001083,
                      ftrstartdate,
                      ftrenddate,
                      histostartdate,
                      histoenddate,
                      scenario_flows,
                      scenario_first_priority,
                      scenario_sf,
                      scenario_histo_sp,
                      conn
                      )

```
</details>

## 𝄜 Retour sur les contraintes du pré-bid
```{python}
# | echo: false

data = [
    {
        "CID_CES": 611104,
        "Nom": "BERLIN_1771_A_LN:ZB16",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"1.5/5",
        "Outage": (
              " ..., 1) Ligne: N_BLOOM 345 KV LINE 3642, du 5 au 10 décembre (Interim Approved)"
        ),
    },
    {
        "CID_CES": 4500004,
        "Nom": "BERLIN1670-2ALN:ZB16",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"1/5",
        "Outage": (
              " ..., 1) Ligne: N_BLOOM 345 KV LINE 3642, du 5 au 10 décembre (Interim Approved)"
        ),
    },
    {
        "CID_CES": 611255,
        "Nom": "BUNKR_HL_1029-2_A_LN:1789",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"1/5",
        "Outage": (
              " Oui, 1) Ligne: BESECK 345 KV LINE 3827: BESECK, du 1er au 12 décembre 2025 (Interim Approved);"
              " Oui, 2) Ligne: S_NAUGTK 115 KV LINE 1142, du 30 nov au 6 déc 2025 (Approved);"
              " Oui, 3) Ligne: BEACN_FL 115 KV LINE 1808-1, du 1er au 12 décembre 2025 (Interim Approved)"
        ),
    },
    {
        "CID_CES": 611251,
        "Nom": "FRSTBRDG_1445_A_LN:1340",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"/5",
        "Outage": (
              " Oui, 1) Ligne: FRSTBRDG 115 KV LINE 1721: FRSTBRDG, du 8 au 23 déc 2025 (Interim Approved);"
              " Oui, 2) Ligne: BESECK 345 KV LINE 3827: BESECK, du 1er au 12 décembre 2025 (Interim Approved);"
              " Oui, 3) Ligne: OXFORD 115 KV LINE 1403, du 7 au 20 déc 2025 (Interim Approved)"
        ),
    },
    {
        "CID_CES": 611330,
        "Nom": "SHAWS_HL_1272_A_LN:1340",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"/5",
        "Outage": (
              " Oui, 1) Ligne: FRSTBRDG 115 KV LINE 1721: FRSTBRDG, du 8 au 23 déc 2025 (Interim Approved);"
              " Oui, 2) Ligne: BESECK 345 KV LINE 3827: BESECK, du 1er au 12 décembre 2025 (Interim Approved);"
              " Oui, 3) Ligne: OXFORD 115 KV LINE 1403, du 7 au 20 déc 2025 (Interim Approved)"
        ),
    },
    {
        "CID_CES": 611258,
        "Nom": "S_NAUGTK_1580_A_LN:1619",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"1/5",
        "Outage": (
              " Oui, 1) Ligne: OXFORD 115 KV LINE 1403, du 7 au 20 déc 2025 (Interim Approved)"
        ),
    },
    {
        "CID_CES": 611410,
        "Nom": "ALLINGS 115 KV LINE 8804A: WOODMONT",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"1/5",
        "Outage": (
              " Oui, 1) Ligne: ALLINGS 115 KV LINE 8804A: WOODMONT, entre le 1er octobre 2025 et le 6 mars 2026 (déjà actif);"
              " Oui, 2) Ligne: BESECK 345 KV LINE 3827: BESECK, du 1er au 12 décembre 2025 (Interim Approved)"
        ),
    },
    {
        "CID_CES": 611310,
        "Nom": "CROWLEYS_62_A_LN:3026",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"3/5",
        "Outage": (
              " Oui, 1) Ligne: KIMBL_RD 115 KV LINE KIMBL_RD 214-1 TO LOVELL (Interim Approved)"
        ),
    },
    {
        "CID_CES": 610873,
        "Nom": "LARRABEE_64_A_LN:3026",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"2.5/5",
        "Outage": (
              " Oui, 1) Ligne: KIMBL_RD 115 KV LINE KIMBL_RD 214-1 TO LOVELL (Interim Approved)"
        ),
    },
    {
        "CID_CES": 1002,
        "Nom": "SUROWIEC - SOUTH INTERFACE (SURO_S)",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"2/5",
        "Outage": (
              ""
        ),
    },
    {
        "CID_CES": 1025,
        "Nom": "NORTHERN NEW ENGLAND - SCOBIE+394 INTERFACE (NS_ST)",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"0.5/5",
        "Outage": (
              ""
        ),
    },
    {
        "CID_CES": 1004,
        "Nom": "MAINE-NEW HAMPSHIRE INTERFACE (MENH)",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"1/5",
        "Outage": (
              ""
        ),
    },
    {
        "CID_CES": 22100708,
        "Nom": "SALEM_T146E-1_A_LN:397",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"2./5",
        "Outage": (
              " Oui, 1) Ligne: W_SALEM 115 KV LINE S145E-2, du 4 au 5 déc (Study). Un seul historique de 2 jours en 2016"
        ),
    },
    {
        "CID_CES": 501358,
        "Nom": "SALEM_T146E-1_A_LN:ACTUAL",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"2.5/5",
        "Outage": (
              " Oui, 1) Ligne: W_SALEM 115 KV LINE S145E-2, du 4 au 5 déc (Study). Un seul historique de 2 jours en 2016"
        ),
    },
    {
        "CID_CES": 4500005,
        "Nom": "STARKS63-2ALN:ZB46",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"1/5",
        "Outage": (
              " Oui, 1) Ligne: HARTLAND 115 KV LINE 82-1, du 8 au 9 déc (Interim Approved);"
              " Oui, 2) Ligne: DETROIT 115 KV LINE 82-2, du 10 au 11 dé (Interim Approved)"
        ),
    },
    {
        "CID_CES": 661405,
        "Nom": "STARKS_278-1_A_LN:WYMK83-5",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"1/5",
        "Outage": (
              " Oui, 1) Ligne: HARTLAND 115 KV LINE 82-1, du 8 au 9 déc (Interim Approved);"
              " Oui, 2) Ligne: DETROIT 115 KV LINE 82-2, du 10 au 11 dé (Interim Approved)"
        ),
    },
    {
        "CID_CES": 22102156,
        "Nom": "WYMAN_HY_83-2_A_LN:63",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"1/5",
        "Outage": (
              " Oui, 1) Ligne: HARTLAND 115 KV LINE 82-1, du 8 au 9 déc (Interim Approved);"
              " Oui, 2) Ligne: DETROIT 115 KV LINE 82-2, du 10 au 11 dé (Interim Approved)"
        ),
    },
    {
        "CID_CES": 610807,
        "Nom": "WEINGART_1732-3_A_LN:ZB09",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"/5",
        "Outage": (
              " Oui, 1) Ligne: WEINGART 115 KV LINE 1732-2: WEINGART, du 3 noc au 5 déc (Approved)"
        ),
    },
    {
        "CID_CES": 610483,
        "Nom": "HARTF_AV_E105_A_LN:F106",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"0.5/5",
        "Outage": (
              " Oui, 1) Ligne: PUTNM_PK 115 KV LINE T172N-6: WOLF_HL"
        ),
    },
    {
        "CID_CES": 610484,
        "Nom": "HARTF_AV_F106_A_LN:E105",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"0.5/5",
        "Outage": (
              " Oui, 1) Ligne: PUTNM_PK 115 KV LINE T172N-6: WOLF_HL"
        ),
    },
    {
        "CID_CES": 1080,
        "Nom": "Burgess Generation (BURG)",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"/5",
        "Outage": (
              " Oui, 1) Ligne: BERLN_NH 115 KV LINE S136: WHITEFLD, 3 jours séparés (Interim Approved)"
        ),
    },
    {
        "CID_CES": 1001,
        "Nom": "ORRINGTON SOUTH (GENERIC CONSTRAINT) INTERFACE (ORR-SO)",
        "Binde": "Oui, ...$ au RT et ...$ au DAM",
        "Potentiel":"/5",
        "Outage": (
              ""
        ),
    }
]

df = pd.DataFrame(data)
# df

from itables import show
import itables.options as opt

opt.maxBytes = 0  # allow long cells
opt.lengthMenu = [10, 25, 50, 100]

show(df)

```
</details>


 


